PdxCodeGuild/class_HB2

- code/Andy/README.md
- code/Andy/python/lab01-average_number.py
accidentally duplicated it ignore the one without the 2
> adding lab 1

- code/matt/python/lab01-mean.py
Lab 01: finding the average.
Version 1 and version 2 are included
> Matt Nichols Lab01 - Finding the mean

- code/matt/python/lab01.py
Last pull request didn't work. Sending up new one
> Matt lab01 average

- code/matt/python/lab04.py
- code/matt/python/lab05.py
> Matt lab04 blackjack

- code/jonpan/lab01.py
Bruce: "Hey, Jonathan.
I see you have a [Lab01](https://github.com/PdxCodeGuild/class_HB2/blob/main/code/jonpan/lab01.py)  on branch main but it doesn't include version 2. The code was merged with [Pull Request 23 Lab 02](https://github.com/PdxCodeGuild/class_HB2/pull/23) but Lab 01 isn't yet complete.
You can follow [Create a new branch for each new lab](https://github.com/PdxCodeGuild/class_HB2/blob/main/0%20General/11%20Git%20Lab%20Workflow.md#create-a-new-branch-for-each-new-lab)  to create a new branch and finish Lab 1. See me or Dustin or Irron if you need assistance."
> resubmitting lab01

- code/muki/lab02.py
Lab 02 done up through version 2.
> Muki lab02 converter

- code/matt/lab06-make-change.py
> Matt lab06 make change

- code/matt/lab05-pick6.py
> Matt lab05 pick6

- code/jonpan/lab05.py
Moved winning ticket outside of loop as requested by Bruce
> jonpan resubmitting lab05 on a new branch

- code/muki/lab04b.py
need some review and whatnot.  Please take a look and let me know folks ^_^
> Muki lab04 blackjackv2

- code/muki/lab03.py
pull request for lab 3. hooray
> commiting lab3 and ready to push

- code/daniel/lab08-dad_api/lab08-dad_api.py
> Daniel lab08 dad api

- code/jonpan/contacts.csv
- code/jonpan/contacts2.csv
- code/jonpan/lab11_v1.py
- code/jonpan/lab11_v2.py
lab11_v1.py = v1
lab11_v2.py = combined v2 and v3
> Submitting lab11

- code/matt/python/lab10-atm.py
Changed the code down below and put exceptions inside the copy and pasted code
> Matt lab10 atm

- code/muki/minicap.py
this is what I had on friday last week
> Muki mini cap

- code/jonpan/lab04.txt
just checking in a .txt file with instructions
repository and code is located here: https://github.com/notvert/notvert.github.io/
> jonpan submitting lab04

- code/kelin/labs/lab08_dad_jokes.py
> Lab 8 dad jokes completed

- code/kelin/labs/lab09_quotes_api.py
> Lab 9 quotes API completed

- code/kelin/labs/lab10_atm.py
Version 1 and 2 of ATM completed
> Kelin lab 10 ATM version 1 and 2

- code/kelin/labs/contacts.csv
- code/kelin/labs/contacts2.csv
- code/kelin/labs/lab11_contacts.py
Version 1 complete working on 2 and 3.
> Kelin lab11 contacts

- code/matt/html_css_flask/lab01_bio/lab01-bio.html
bio is complete. All work is done in the html file, not inside the css file
> Matt lab01 bio

- code/daniel/python_files/lab05-pick6/lab05-pick6.py
> Daniel lab05 pick6

- code/kelin/labs/html/lab06_flask_redo.py
- code/kelin/labs/html/templates/converter.html
- code/kelin/labs/html/templates/converter2.html
- code/kelin/labs/html/templates/index.html
> Lab 6 Flask redo unit converter

- code/matt/html_css_flask/lab06_flask_redo_unit_converter/app.py
- code/matt/html_css_flask/lab06_flask_redo_unit_converter/template/index.html
I've finally learned how to create a little project in flask!!
> lab06 flask redo complete

- code/kelin/labs/javascript/lab01_redo/average_numbers_redo.js
- code/kelin/labs/javascript/lab01_redo/index.html
Completed Version 1 and 2 of Average Numbers in Javascript.
> Kelin lab01 jsredo

- code/daniel/js_files/daniel-weatherAPI/.gitignore
- code/daniel/js_files/daniel-weatherAPI/index.html
- code/daniel/js_files/daniel-weatherAPI/weatherAPI.js
> Daniel js lab02 weather api

- code/kelin/labs/javascript/calculator/calculations.js
- code/kelin/labs/javascript/calculator/calculator.css
- code/kelin/labs/javascript/calculator/calculator.html
Completed calculator and tested
> Kelin lab calculator

- code/matt/javascript/lab01_javascript_redo/index.html
- code/matt/javascript/lab01_javascript_redo/redo.js
Lab finished. Nothing special with it, and no troubleshooting fixes. If you click 5 + 5 (or whatever number), it'll give you your mean. Type 'done' to back out of it. Otherwise, you won't be able to exit my while loop (I did that on purpose)
> Matt lab01 redo js

- code/kelin/labs/javascript/vue_redo/redo.html
- code/kelin/labs/javascript/vue_redo/redo.vue
Completed Unit converter Vue redo
> Kelin lab vueredo

- code/daniel/js_files/daniel-vueRedo/index.html
- code/daniel/js_files/daniel-vueRedo/previousConverterLab.py
- code/daniel/js_files/daniel-vueRedo/sample.html
> Daniel js lab04 vue redo
